.Dd March 2, 2001
.Dt FRESHPORTS 1
.Sh NAME
.Nm freshports
.Nd register installed packages with FreshPorts
.Sh SYNOPSIS
.Nm
.Op Fl d
.Op Fl -version
.Sh DESCRIPTION
.Nm Freshports
is a script for retrieving the contents of pkg_info and registering 
installed ports with FreshPorts.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Turns on verbose output.
.It Fl -version
Prints version information
.El
.Sh SEE ALSO
The FreshPorts website:  http://www.FreshPorts.org/
.Sh AUTHOR
John P. Campbell
.Sh HISTORY
The
.Nm
command first appeared in FreeBSD 4.x
